### ISSUE TITLE
Observable vs Flowable Support

### ISSUE THREAD

**Issue by thomasnield** [davidmoten/rxjava2-extras#6]
Hey David, 

Do you think this project should only support Flowable operators? Or will there be plans for Observable support as well? 

Thomas N.

**Comment by thomasnield** [comment]
By the way, I am drafting up a pull request to help port over some functionality from rxjava-extras.

**Comment by davidmoten** [comment]
Observable as well. Transformers distinguished by package.

**Comment by thomasnield** [comment]
Okay thanks!
