### ISSUE TITLE
 Bad interleaving found that causes test failure

### ISSUE THREAD

**Issue by Alisha-0321** [davidmoten/rxjava2-extras#94]
commit version- d0315b6ecb0d24437ec0d440b6d768e89247d56c

Describe the bug
It is possible to encounter an unexpected crash due to a bad thread interleaving. The bad interleaving may occur due to sharing one variable (variable name is cancelled). For example, I saw at Line 53 and at Line 66 of FlowableRepeat.java, they share the same variable. Of these two accesses one method is writing on that variable at Line 66 and another Line at 53 reads the value of that variable. However, this may cause a crash anytime if multiple threads interleave in different ways.

Expected behavior
No error or sudden crash of the program is expected.

Additional context
When I investigated the FlowableRepeat class, I found that the cancelled variable is used on Line 53 and Line 66. Of these two access, one is a write operation. Hence, any unexpected crash or inconsistency may occur if multiple threads interleave.

Environment(please complete the following information):
I ran the test on an Ubuntu 20.04 LTS machine using OpenJDK 1.8.0_312.

**Comment by davidmoten** [comment]
ok I'll have a look

**Comment by davidmoten** [comment]
You state 

>However, this may cause a crash anytime if multiple threads interleave in different ways.

Crash? Be aware that cancellation can expect a best endeavours response only from an Observable/Flowable. This may mean that you get one or more extra emissions than you expect "after" cancellation. All operators have little races like this. The variable `cancelled` is declared volatile so there are no visibility issues between threads.

Can you be more specific about what you mean by a crash?

**Comment by davidmoten** [comment]
Closing due to lack of further information.
